<?php
$cacheprid=44003732;
$cachecompanyid=15;
$cachecontenttypeid=250;
$cacheacctnumber=0;
$cachereleaseheadline='techno-offers-educational-cnc-package';
$cachebasicwrite='<a href=\"http://cfnewsads.thomasnet.com/images/sites/4/2013/02/Techno-CNC-Package.jpg\"><img class=\"alignleft size-full wp-image-3733\" alt=\"Techno CNC Package\" src=\"http://cfnewsads.thomasnet.com/images/sites/4/2013/02/Techno-CNC-Package.jpg\" width=\"240\" height=\"261\" /></a><a href=\"http://www.techedcnc.com/\">Techno, Inc. Education Systems</a> is now selling a packaged educational CNC machining deal for schools looking to improve their STEM and machining course offerings.<br />
<br />
<a href=\"http://www.techno-isel.com/Education1/Press/LCT-3024Package.htm\">The Complete Techno Educational CNC Machining Package</a> is being offered at a discounted price of $18,450 for school programs. The package includes:<br />
<br />
Techno 30 x 24 inch Servo CNC Router<br />
<br />
·    Introduction to CNC Machining Curriculum Kit<br />
<br />
·    5 Licensed Seats of Mastercam X6 Software<br />
<br />
·    3.25 Horsepower Porter Cable Spindle<br />
<br />
·    Heavy Duty Machine Stand<br />
<br />
·    Wood and Plastic Tool Kit<br />
<br />
·    Custom Curriculum Tool Kit<br />
<br />
·    Set of 4 CAM Clamps<br />
<br />
·    Set of 7 inch Bar Clamp Stops<br />
<br />
·    Set of 9 inch Bar Clamps Stops<br />
<br />
·    1/2, 1/4 and 3/8 inch Collets<br />
<br />
·    Spindle Wrenches<br />
<br />
·    Setup and Installation<br />
<br />
-<a href=\"https://twitter.com/BrianL_TN\">Brian Lane</a>';
$cachebodytext='Techno, Inc. Education Systems is now offering a packaged CNC machining deal for schools looking to improve their STEM and machining courses.';
$cachecompanyname='Brian Lane';
$cachecompanystreet='';
$cachecompanystreet2='';
$cachecompanycity='';
$cachecompanystate='';
$cachecompanyzip='';
$cachecompanycountry='';
$cachecompanytelephone='';
$cachecompanyfax='';
$cachecompanyurl='';
$cacheienheadline='Techno Offers Educational CNC Package';
$cacheiensubheadline='';
$cachevalidurl='/machining/2013/02/20/techno-offers-educational-cnc-package';
$cacheurlname='';
$cacheurltext='';
$cachedirinfo='2013-02-20 18:04:58';
$cachestatusid=298;
$cachereldate="February 20, 2013";
$cachepubdate="February 20, 2013";
$cacheEmbededSRC='';
$cachegoodprofile=0;
?>