<?php
$cacheprid=44003761;
$cachecompanyid=15;
$cachecontenttypeid=250;
$cacheacctnumber=0;
$cachereleaseheadline='bobcad-cam-unveils-grant-program-for-small-business-assistance';
$cachebasicwrite='<a href=\"http://www.bobcad.com/\" target=\"_blank\">BobCAD-CAM</a> has started a new <a href=\"http://www.bobcad.com/articles/cnc-machining-software-company-launches-participation-grant-program-for-small-businesses.php\" target=\"_blank\">Participation Grant Program</a> to provide business and employment training assistance to small American businesses who have suffered from foreign competition.<br />
<br />
The software company will accept applications from U.S. small businesses to help analyze and revamp business practices in that company. BobCAD-CAM will send dedicated professionals to analyze of \"employee development training, new project development and marketing\" as well as mentor engineers, according to a <a href=\"http://www.prweb.com/releases/2013/2/prweb10443206.htm\" target=\"_blank\">statement</a>.<br />
<br />
The program also provides general business plan diagnostics gathering to analyze where a company needs improvement and how to fill those holes via a \"Plan of Attack.\"<br />
<br />
BobCAM-CAM will split project costs with the company to allow small companies to take advantage of the program. You can watch a video about the Participation Grant Program below.<br />
<br />
<iframe src=\"http://www.youtube.com/embed/1IuaeT32T4k\" height=\"315\" width=\"420\" allowfullscreen=\"\" frameborder=\"0\"></iframe><br />
<br />
-<a href=\"https://twitter.com/BrianL_TN\">Brian Lane</a>';
$cachebodytext='BobCAD-CAM has started a new Participation Grant Program to provide business and employment training assistance to small American businesses who have suffered from foreign competition.';
$cachecompanyname='Brian Lane';
$cachecompanystreet='';
$cachecompanystreet2='';
$cachecompanycity='';
$cachecompanystate='';
$cachecompanyzip='';
$cachecompanycountry='';
$cachecompanytelephone='';
$cachecompanyfax='';
$cachecompanyurl='';
$cacheienheadline='BobCAD-CAM Unveils Grant Program for Small Business Assistance';
$cacheiensubheadline='';
$cachevalidurl='/machining/2013/02/22/bobcad-cam-unveils-grant-program-for-small-business-assistance';
$cacheurlname='';
$cacheurltext='';
$cachedirinfo='2013-02-22 18:54:35';
$cachestatusid=298;
$cachereldate="February 22, 2013";
$cachepubdate="February 22, 2013";
$cacheEmbededSRC='';
$cachegoodprofile=0;
?>