<?php
$cacheprid=44003765;
$cachecompanyid=15;
$cachecontenttypeid=250;
$cacheacctnumber=0;
$cachereleaseheadline='how-does-3-d-printing-impact-conventional-manufacturing';
$cachebasicwrite='[caption id=\"attachment_3766\" align=\"alignleft\" width=\"215\"]<a href=\"http://cfnewsads.thomasnet.com/images/sites/4/2013/02/Dimension-3d-printer.jpg\"><img class=\"size-full wp-image-3766\" style=\"border: 5px solid black;\" alt=\"Dimension 3d printer\" src=\"http://cfnewsads.thomasnet.com/images/sites/4/2013/02/Dimension-3d-printer.jpg\" width=\"215\" height=\"246\" /></a> A Dimension 3-D printer like that purchased by Jesel Inc. Source: Dimension Printing[/caption]<br />
<br />
How is 3-D printing impacting the conventional machining and manufacturing industry spaces? So asks a recent piece in <a href=\"http://www.mmsonline.com/blog/post/3d-printings-expanding-role\" target=\"_blank\">Modern Machine Shop</a> (MMS) that profiles engine component manufacturer <a href=\"http://www.jesel.com/innovation/\" target=\"_blank\">Jesel Inc.</a>\'s experience purchasing and using a 3-D printer in its facility.<br />
<br />
Joining the chorus of other 3-D printer converts, Jesel has found their Dimension 3-D printer producing prototypes for customers as well as functioning as a marketing tool at trade shows. Indeed, MMS  notes that using the Dimension printer has allowed Jesel to pay for it several times over.<br />
<br />
\"If communication between people was perfect, then Jesel Inc. would rarely need prototyping,\" Jesel manager Ray Frattone told MMS. But having access to the speedy, low cost prototyping ability of the printer bridges that communication gulf, showing customers - and potential customers - exactly what the company is capable of.<br />
<br />
Has your company investigated 3-D printing as a component to conventional industry practices? Please tell us if you have any experience trying 3-D printing, whether it worked out for you or didn\'t.<br />
<br />
-<a href=\"https://twitter.com/BrianL_TN\" target=\"_blank\">Brian Lane</a>';
$cachebodytext='How is 3-D printing impacting the conventional machining and manufacturing industry spaces? ';
$cachecompanyname='Brian Lane';
$cachecompanystreet='';
$cachecompanystreet2='';
$cachecompanycity='';
$cachecompanystate='';
$cachecompanyzip='';
$cachecompanycountry='';
$cachecompanytelephone='';
$cachecompanyfax='';
$cachecompanyurl='';
$cacheienheadline='How Does 3-D Printing Impact Conventional Manufacturing?';
$cacheiensubheadline='';
$cachevalidurl='/machining/2013/02/22/how-does-3-d-printing-impact-conventional-manufacturing';
$cacheurlname='';
$cacheurltext='';
$cachedirinfo='2013-02-22 18:31:23';
$cachestatusid=298;
$cachereldate="February 22, 2013";
$cachepubdate="February 22, 2013";
$cacheEmbededSRC='';
$cachegoodprofile=0;
?>